// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

/*=========================Update 2==================================*/
// import type { Metadata } from "next";
// // import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({children}: Readonly<{
//   children: React.ReactNode}>) {
//   return (
//     <html lang="en">
//       <body>
//         {children}
//       </body>
//     </html>
//   );
// }

/*=========================Update 2==================================*/
// import type { Metadata } from "next";
// // import "./globals.css";
// import Link from "next/link"; // New import for navigation

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({children}: Readonly<{
//   children: React.ReactNode}>) {
//   return (
//     <html lang="en">
//       <body>

//         {/* New: Code for the header  */}
//         <header style={{ padding: "1rem", background: "#4be9d6ff" }}>
//           <nav style={{ display: "flex", gap: "1rem" }}>
//             <Link href="/">Home</Link>
//             <Link href="/about">About</Link>
//           </nav>
//         </header>

//         <main style={{padding:"1rem"}}>
//           {children}
//         </main>

//       </body>
//     </html>
//   );
// }

/*=========================Update 2==================================*/
// import Link from "next/link";
// import "./globals.css";

// export const metadata = {
//   title: "My First App",
//   description: "Learning Next.js step by step",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{ children: React.ReactNode }>) {
//   return (
//     <html lang="en">
//       <body className="bg-gray-50 text-gray-900">
//         <header className="bg-gray-100 shadow-sm">
//           <nav className="max-w-4xl mx-auto flex items-center gap-6 p-4">
//             <Link href="/" className="text-blue-500 hover:underline">
//               Home
//             </Link>
//             <Link href="/about" className="text-blue-500 hover:underline">
//               About
//             </Link>
//             <Link href="/posts" className="text-blue-500 hover:underline">
//               Posts
//             </Link>
//           </nav>
//         </header>

//         <main className="max-w-4xl mx-auto p-4">{children}</main>
//       </body>
//     </html>
//   );
// }

/*=========================Update 2==================================*/
import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "My Next.js App",
  description: "Learning Next.js step by step",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900">
        <header className="bg-gray-100 shadow-sm">
          <nav className="max-w-4xl mx-auto flex items-center gap-6 p-4">
            <Link href="/" className="text-blue-600 hover:text-blue-800">
              Home
            </Link>

            <Link href="/about" className="text-blue-600 hover:text-blue-800">
              About
            </Link>

            <Link href="/movies" className="text-blue-600 hover:text-blue-800">
              Movies
            </Link>
          </nav>
        </header>

        <main className="max-w-4xl mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
