// import type { Metadata } from "next";
// import Link from "next/link";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({children}: Readonly<{
//   children: React.ReactNode}>) {
//   return (
//     <html lang="en">
//       <body>
//         <header style={{ padding: "1rem", background: "#f3f3f3" }}>
//           <nav style={{ display: "flex", gap: "1rem" }}>
//             <Link href="/">Home</Link>
//             <Link href="/about">About</Link>
//           </nav>
//         </header>

//         <main style={{padding:"1rem"}}>
//           {children}
//         </main>

//       </body>
//     </html>
//   );
// }

/*====================UPDATE 2=============================*/
// import Link from "next/link";
// import './globals.css';

// export const metadata = {
//   title: "My Next.js App",
//   description: "Learning Next.js step by step",
// };

// export default function RootLayout({ children }:Readonly<{children: React.ReactNode}>) {
//   return (
//     <html lang="en">
//       <body className="bg-gray-50 text-gray-900">
//         <header className="bg-gray-100 shadow-sm">
//           <nav className="max-w-4xl mx-auto flex items-center gap-6 p-4">
//             <Link href="/" className="hover:underline">
//               Home
//             </Link>
//             <Link href="/about" className="hover:underline">
//               About
//             </Link>
//             <Link href="/posts" className="hover:underline">
//               Posts
//             </Link>
//           </nav>
//         </header>

//         <main className="max-w-4xl mx-auto p-4">
//           {children}
//         </main>
//       </body>
//     </html>
//   );
// }




/*====================UPDATE 3=============================*/
import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "My Next.js App",
  description: "Learning Next.js step by step",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900">
        <header className="bg-gray-100 shadow-sm">
          <nav className="max-w-4xl mx-auto flex items-center gap-6 p-4">
            <Link href="/" className="hover:text-blue-800">
              Home
            </Link>

            <Link href="/about" className=" hover:text-blue-800">
              About
            </Link>

            <Link href="/movies" className=" hover:text-blue-800">
              Movies
            </Link>
          </nav>
        </header>

        <main className="max-w-4xl mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
